name: licenses
services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: licenses
    ports:
      - "5432:5432"
    volumes:
      - licenses_data:/var/lib/postgresql/data

volumes:
  licenses_data:
